### ISSUE TITLE
Problems with epSep and epDot Calculations

### ISSUE THREAD

**Issue by aechavez** [juan-mlr/ecal-bdt#13]
The uncommented code for the epSep and epDot calculations do not work out of the box. The full error log that I run into when I uncomment lines 35, 36, 217, 218, 228, and 229 is as follows:

[bash-4.2$ ldmx python3 treeMaker.py -i $PWD/test_input.root -g test_output -o $PWD

Preparing test_output
Using scratch path /nfs/slac/g/ldmx/users/aechavez/ldmx-sw-v3.0.0-w-container/bdt/scratch
Creating tmp directory /nfs/slac/g/ldmx/users/aechavez/ldmx-sw-v3.0.0-w-container/bdt/scratch/tmp_0
Copying input files into tmp directory
test_input.root

Running test_output
Processing Event: 0
Traceback (most recent call last):
  File "treeMaker.py", line 516, in <module>
    main()
  File "treeMaker.py", line 139, in main
    proc.run(maxEvents=maxEvent)
  File "/nfs/slac/g/ldmx/users/aechavez/ldmx-sw-v3.0.0-w-container/bdt/mods/ROOTmanager.py", line 147, in run
    self.event_process(self)
  File "treeMaker.py", line 218, in event_process
    feats['epDot'] = physTools.dot(e_norm,g_norm)
UnboundLocalError: local variable 'e_norm' referenced before assignment

**Comment by aechavez** [comment]
My naive fix for this bug is to simply move lines 234 and 235 to just before the block at 216. Is this the correct approach?
